name: go linux build 
on:
  push:
    tags:
      - ".*build"
jobs:
 ubuntu:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: apt update
      run:
       sudo apt-get update &&
       sudo apt-get upgrade &&
       sudo apt-get install make zlib1g-dev libssl-dev gperf  cmake g++

    - name: git clone
      run: git clone https://github.com/tdlib/td.git

    - name: mkdir build
      run: cd td &&rm -rf build&& mkdir build&&cd build&&ls .

    - name: build setting
      run: 
        cd td/build &&
        export CXXFLAGS=""&&
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr/local ..

    - name: build install
      run: cd td/build && sudo cmake --build . --target install

    - name: go build 
      run: cd src && sudo  go build -o ./dist/main

    - uses: actions/upload-artifact@v2
      with:
        name: go-build
        path: src/dist/