name: go linux build 
on:
  push:
jobs:
  windows:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: apt install 
      run: sudo apt-get install make git zlib1g-dev libssl-dev gperf php cmake g++

    - name: install td/tdlib/
      run:  cd tdlib/linux && sudo sh ./install.sh

    - name: show go version
      run: go version 

    - name: go build 
      run: cd src && sudo  go build -o ./dist/test

    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: src/dist/test